"""Add last_reset_token to users

Revision ID: 064a1c57ad75
Revises: 9fa8ac43ca4a
Create Date: 2025-10-12 14:34:05.946445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064a1c57ad75'
down_revision = '9fa8ac43ca4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_reset_token')

    # ### end Alembic commands ###
