"""Add missing columns

Revision ID: 66c0d3739db6
Revises: 6f8623aefc81
Create Date: 2025-10-17 23:42:17.924656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c0d3739db6'
down_revision = '6f8623aefc81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('social_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('last_reset_token', sa.String(length=512), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_reg_no_key'), type_='unique')
        batch_op.drop_column('reg_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('users_reg_no_key'), ['reg_no'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('last_reset_token')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('social_provider')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
