"""Add users table

Revision ID: 6f8623aefc81
Revises: 9690d53cc92f
Create Date: 2025-10-14 01:43:42.754326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8623aefc81'
down_revision = '9690d53cc92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('reg_no', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['reg_no'])
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('social_provider')
        batch_op.drop_column('is_active')
        batch_op.drop_column('username')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('last_reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('social_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reg_no')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
