"""Added appeals module

Revision ID: 84e45f220ee6
Revises: d6a39053c9ef
Create Date: 2026-05-31 22:01:21.549449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e45f220ee6'
down_revision = 'd6a39053c9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(length=120), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('violation_id', sa.String(length=100), nullable=True),
    sa.Column('violation_date', sa.Date(), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=True),
    sa.Column('fine_amount', sa.Integer(), nullable=True),
    sa.Column('appeal_reason', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_admin', sa.String(length=120), nullable=True),
    sa.Column('admin_comments', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeals')
    # ### end Alembic commands ###
