"""create zones and incidents tables

Revision ID: b636539cac4c
Revises: 84e45f220ee6
Create Date: 2026-06-01 12:12:58.922969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b636539cac4c'
down_revision = '84e45f220ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_name')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=False),
    sa.Column('incident_time', sa.String(length=8), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(), nullable=False),
    sa.Column('vape_detected', sa.Boolean(), nullable=True),
    sa.Column('smoke_cam_detected', sa.Boolean(), nullable=True),
    sa.Column('smoke_sensor_value', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_table('zones')
    # ### end Alembic commands ###
