"""add 2fa fields to user model

Revision ID: d6a39053c9ef
Revises: 66c0d3739db6
Create Date: 2025-10-26 20:36:33.036653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a39053c9ef'
down_revision = '66c0d3739db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_2fa_dismissed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.drop_column('last_2fa_dismissed_at')
        batch_op.drop_column('is_2fa_enabled')

    # ### end Alembic commands ###
